name: Build Linux wheels

on:
  workflow_call:
    inputs:
      build-commit:
        required: true
        type: string
      artifacts-name:
        required: true
        type: string

env:
  REPO_DIR: Pillow
  TEST_DEPENDS: "pytest pytest-timeout"

jobs:
  build:
    name: ${{ matrix.platform }} ${{ matrix.mb-ml-libc }}${{ matrix.mb-ml-ver }} ${{ matrix.python }}
    runs-on: "ubuntu-20.04"
    strategy:
      fail-fast: false
      matrix:
        python: [
          "pypy3.8-7.3.11",
          "pypy3.9-7.3.11",
          "3.8",
          "3.9",
          "3.10",
          "3.11",
        ]
        platform: [ "aarch64", "i686", "x86_64" ]
        mb-ml-libc: [ "manylinux", "musllinux" ]
        mb-ml-ver: [ 2014, "_1_1", "_2_28" ]
        exclude:
          - python: "pypy3.8-7.3.11"
            mb-ml-libc: "musllinux"
          - python: "pypy3.9-7.3.11"
            mb-ml-libc: "musllinux"
          - platform: "i686"
            mb-ml-ver: "_1_1"
          - platform: "i686"
            mb-ml-ver: "_2_28"
          - mb-ml-libc: "musllinux"
            mb-ml-ver: 2014
          - mb-ml-libc: "manylinux"
            mb-ml-ver: "_1_1"
          - mb-ml-libc: "musllinux"
            mb-ml-ver: "_2_28"
    env:
      BUILD_COMMIT: ${{ inputs.build-commit }}
      PLAT: ${{ matrix.platform }}
      MB_PYTHON_VERSION: ${{ matrix.python }}
      MB_ML_LIBC: ${{ matrix.mb-ml-libc }}
      MB_ML_VER: ${{ matrix.mb-ml-ver }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Build Wheel
        run: .github/workflows/build.sh
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifacts-name }}
          path: wheelhouse/*.whl
      # Uncomment to get SSH access for testing
      # - name: Setup tmate session
      #   if: failure()
      #   uses: mxschmitt/action-tmate@v3
